### ISSUE TITLE
libijkffmpeg.so has text relocations

### ISSUE THREAD

**Issue by fukemy** [l123456789jy/ijkplayer#10]
Hello. I got this error when running in android M simulator. Can you help?

**Comment by fukemy** [comment]
<img width="365" alt="screen shot 2018-09-25 at 14 04 04" src="https://user-images.githubusercontent.com/8202437/45998540-5e6f9600-c0cd-11e8-9bbc-7b5aed908940.png">

**Comment by l123456789jy** [comment]
@fukemy Please do not run in the simulator, the simulator may be missing some libraries

**Comment by fukemy** [comment]
tks. really sad about simulator
