### ISSUE TITLE
怎么编译ijkpalyer让其对https开头的url能播放？能给多点详细信息吗？mpeg4编码的视频好像看不了

### ISSUE THREAD

**Issue by lijie815917** [l123456789jy/ijkplayer#3]

**Comment by l123456789jy** [comment]
http://www.jianshu.com/p/8673ca24e9b0

**Comment by lijie815917** [comment]
不行，我编译
build on Darwin x86_64
ANDROID_NDK=/Users/lijie/eclipse/android-sdk-macosx/ndk-bundle
IJK_NDK_REL=13.1.3345770
NDKr13.1.3345770 detected
HOST_OS=darwin
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=darwin-x86_64
HOST_NUM_CPUS=4
BUILD_NUM_CPUS=8
Auto-config: --arch=arm
Refusing to clobber existing install directory: /Users/lijie/experiment/ijkplayer-android/android/contrib/build/openssl-armv5/toolchain.

make-standalone-toolchain.sh used to install a new toolchain into an existing
directory. This is not desirable, as it will not clean up any stale files. If
you wish to remove the install directory before creation, pass --force.

**Comment by l123456789jy** [comment]
@lijie815917 我这个是可以支持https，你播放不了吗？我没有出现这种问题,看你这个好像不是在乌班图下编译的，如果不是最好在乌班图下编译。源码要去ijkplay的仓库拉取，不要使用网上找到。

**Comment by lijie815917** [comment]
我知道原因了，我是在mac编码的，最新版本latest分支不支持ndkr10e以上的版本，需要切换回master版本，而且需要将contrib/build文件夹删除。或者直接用旧版本ndkr10e编译
