### ISSUE TITLE
不能本地播放

### ISSUE THREAD

**Issue by Icando26** [l123456789jy/ijkplayer#6]
网络播放时可以的，但是本地不能播放 -10000

**Comment by l123456789jy** [comment]
@Icando26 本地播放什么格式的视频？

**Comment by Icando26** [comment]
mkv

**Comment by Icando26** [comment]
网络也是mkv就可以

**Comment by l123456789jy** [comment]
看下日志把你的错误日志到 https://github.com/Bilibili/ijkplayer/issues 里面搜搜看有没有，我是按照默认支持的格式编译的。@Icando26
